apiVersion: apps/v1
kind: Deployment
metadata:
  name: ing-nf-nac-dep
  namespace: poc-event-driven-ns
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ingestor-nf-nacionalizacao-worker
  template:
    metadata:
      labels:
        app: ingestor-nf-nacionalizacao-worker
    spec:
      containers:
      - name: ingestor-nf-nacionalizacao-worker
        image: maxandriani/poc.eventdriven.app.dwnfconsolidacaoworker:1.0.10
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: ingestor-nf-nacionalizacao-config
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: ing-nf-na-p
          initialDelaySeconds: 30
          periodSeconds: 60
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: ing-nf-na-p
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 30
        ports:
        - containerPort: 80
          name: ing-nf-na-p
