apiVersion: apps/v1
kind: Deployment
metadata:
  name: ing-nf-grpc-dep
  namespace: poc-event-driven-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ing-nf-grpc
  template:
    metadata:
      labels:
        app: ing-nf-grpc
    spec:
      containers:
      - name: ing-nf-grpc
        image: maxandriani/poc.eventdriven.app.nfingestorgrpc:1.0.2
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: ing-nf-grpc-config
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
          requests:
            memory: "192Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
          name: ing-nf-grpc-p
