apiVersion: v1
kind: Service
metadata:
  name: ing-nf-grpc-svc
  namespace: poc-event-driven-ns
spec:
  type: LoadBalancer
  selector:
    app: ing-nf-grpc
  ports:
  - port: 5002
    targetPort: ing-nf-grpc-p
