apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestor-nf-exportacao-config
  namespace: poc-event-driven-ns
data:
  ConnectionStrings__ConsolidacaoServiceBusSubscription: ...
  ConnectionStrings__DwNfDatabase: User ID=postgres;Password=postgres;Host=raspberrypi;Port=5432;Database=regimes;Pooling=true;Connection Lifetime=0;
  ConnectionStrings__NotasFiscaisStorage: ...
  ServiceBus__ConsolidacaoServiceBusSubscription__TopicName: nf_ingress_tp
  ServiceBus__ConsolidacaoServiceBusSubscription__SubscriptionName: exportacao_worker_sub
