apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: poc-event-driven-ns
spec:
  type: LoadBalancer
  selector:
    app: postgres-db
  ports:
  - port: 5432
    targetPort: postgres-db-port
