// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nfingress/v1/nfs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Poc.EventDriven.Protos.NfIngress.V1 {

  /// <summary>Holder for reflection information generated from nfingress/v1/nfs.proto</summary>
  public static partial class NfsReflection {

    #region Descriptor
    /// <summary>File descriptor for nfingress/v1/nfs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NfsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZuZmluZ3Jlc3MvdjEvbmZzLnByb3RvEhxwb2MuZXZlbnRkcml2ZW4ubmZp",
            "bmdyZXNzLnYxGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvIkQK",
            "EE5mRW1wcmVzYU1lc3NhZ2USDAoEY25wahgBIAEoCRIMCgRub21lGAIgASgJ",
            "EhQKDHJhemFvX3NvY2lhbBgDIAEoCSLmAQoNTmZJdGVtTWVzc2FnZRILCgNz",
            "a3UYASABKAkSEQoJZGVzY3JpY2FvGAIgASgJEhIKCnF1YW50aWRhZGUYAyAB",
            "KAUSEQoJdmFsb3JfYnJsGAQgASgFEhYKDnZhbG9yX2ljbXNfYnJsGAUgASgF",
            "EhgKEHZhbG9yX2ljbXNzdF9icmwYBiABKAUSFAoMdmFsb3JfaWlfYnJsGAcg",
            "ASgFEhUKDXZhbG9yX2lwaV9icmwYCCABKAUSFQoNdmFsb3JfcGlzX2JybBgJ",
            "IAEoBRIYChB2YWxvcl9jb2ZpbnNfYnJsGAogASgFIrwDCglOZk1lc3NhZ2US",
            "DQoFY2hhdmUYASABKAkSDgoGbnVtZXJvGAIgASgFEg0KBXNlcmllGAMgASgF",
            "Ej8KB2VtcHJlc2EYBCABKAsyLi5wb2MuZXZlbnRkcml2ZW4ubmZpbmdyZXNz",
            "LnYxLk5mRW1wcmVzYU1lc3NhZ2USRwoKZXhwb3J0YWRvchgFIAEoCzIuLnBv",
            "Yy5ldmVudGRyaXZlbi5uZmluZ3Jlc3MudjEuTmZFbXByZXNhTWVzc2FnZUgA",
            "iAEBEj8KB2VtaXNzb3IYBiABKAsyLi5wb2MuZXZlbnRkcml2ZW4ubmZpbmdy",
            "ZXNzLnYxLk5mRW1wcmVzYU1lc3NhZ2USKwoHZW1pc3NhbxgHIAEoCzIaLmdv",
            "b2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASPgoIb3BlcmFjYW8YCCABKA4yLC5w",
            "b2MuZXZlbnRkcml2ZW4ubmZpbmdyZXNzLnYxLk5mVGlwb09wZXJhY2FvEjoK",
            "BWl0ZW1zGAkgAygLMisucG9jLmV2ZW50ZHJpdmVuLm5maW5ncmVzcy52MS5O",
            "Zkl0ZW1NZXNzYWdlQg0KC19leHBvcnRhZG9yKmwKDk5mVGlwb09wZXJhY2Fv",
            "EiAKHE5GX1RJUE9fT1BFUkFDQU9fVU5TUEVDSUZJRUQQABIcChhORl9USVBP",
            "X09QRVJBQ0FPX0VOVFJBREEQARIaChZORl9USVBPX09QRVJBQ0FPX1NBSURB",
            "EAJCJqoCI1BvYy5FdmVudERyaXZlbi5Qcm90b3MuTmZJbmdyZXNzLlYxYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Poc.EventDriven.Protos.NfIngress.V1.NfTipoOperacao), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage), global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage.Parser, new[]{ "Cnpj", "Nome", "RazaoSocial" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Poc.EventDriven.Protos.NfIngress.V1.NfItemMessage), global::Poc.EventDriven.Protos.NfIngress.V1.NfItemMessage.Parser, new[]{ "Sku", "Descricao", "Quantidade", "ValorBrl", "ValorIcmsBrl", "ValorIcmsstBrl", "ValorIiBrl", "ValorIpiBrl", "ValorPisBrl", "ValorCofinsBrl" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Poc.EventDriven.Protos.NfIngress.V1.NfMessage), global::Poc.EventDriven.Protos.NfIngress.V1.NfMessage.Parser, new[]{ "Chave", "Numero", "Serie", "Empresa", "Exportador", "Emissor", "Emissao", "Operacao", "Items" }, new[]{ "Exportador" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum NfTipoOperacao {
    [pbr::OriginalName("NF_TIPO_OPERACAO_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("NF_TIPO_OPERACAO_ENTRADA")] Entrada = 1,
    [pbr::OriginalName("NF_TIPO_OPERACAO_SAIDA")] Saida = 2,
  }

  #endregion

  #region Messages
  public sealed partial class NfEmpresaMessage : pb::IMessage<NfEmpresaMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NfEmpresaMessage> _parser = new pb::MessageParser<NfEmpresaMessage>(() => new NfEmpresaMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NfEmpresaMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Poc.EventDriven.Protos.NfIngress.V1.NfsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NfEmpresaMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NfEmpresaMessage(NfEmpresaMessage other) : this() {
      cnpj_ = other.cnpj_;
      nome_ = other.nome_;
      razaoSocial_ = other.razaoSocial_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NfEmpresaMessage Clone() {
      return new NfEmpresaMessage(this);
    }

    /// <summary>Field number for the "cnpj" field.</summary>
    public const int CnpjFieldNumber = 1;
    private string cnpj_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Cnpj {
      get { return cnpj_; }
      set {
        cnpj_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nome" field.</summary>
    public const int NomeFieldNumber = 2;
    private string nome_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nome {
      get { return nome_; }
      set {
        nome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "razao_social" field.</summary>
    public const int RazaoSocialFieldNumber = 3;
    private string razaoSocial_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RazaoSocial {
      get { return razaoSocial_; }
      set {
        razaoSocial_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NfEmpresaMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NfEmpresaMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cnpj != other.Cnpj) return false;
      if (Nome != other.Nome) return false;
      if (RazaoSocial != other.RazaoSocial) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Cnpj.Length != 0) hash ^= Cnpj.GetHashCode();
      if (Nome.Length != 0) hash ^= Nome.GetHashCode();
      if (RazaoSocial.Length != 0) hash ^= RazaoSocial.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Cnpj.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cnpj);
      }
      if (Nome.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nome);
      }
      if (RazaoSocial.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RazaoSocial);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Cnpj.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Cnpj);
      }
      if (Nome.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nome);
      }
      if (RazaoSocial.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RazaoSocial);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Cnpj.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cnpj);
      }
      if (Nome.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nome);
      }
      if (RazaoSocial.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RazaoSocial);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NfEmpresaMessage other) {
      if (other == null) {
        return;
      }
      if (other.Cnpj.Length != 0) {
        Cnpj = other.Cnpj;
      }
      if (other.Nome.Length != 0) {
        Nome = other.Nome;
      }
      if (other.RazaoSocial.Length != 0) {
        RazaoSocial = other.RazaoSocial;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Cnpj = input.ReadString();
            break;
          }
          case 18: {
            Nome = input.ReadString();
            break;
          }
          case 26: {
            RazaoSocial = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Cnpj = input.ReadString();
            break;
          }
          case 18: {
            Nome = input.ReadString();
            break;
          }
          case 26: {
            RazaoSocial = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NfItemMessage : pb::IMessage<NfItemMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NfItemMessage> _parser = new pb::MessageParser<NfItemMessage>(() => new NfItemMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NfItemMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Poc.EventDriven.Protos.NfIngress.V1.NfsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NfItemMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NfItemMessage(NfItemMessage other) : this() {
      sku_ = other.sku_;
      descricao_ = other.descricao_;
      quantidade_ = other.quantidade_;
      valorBrl_ = other.valorBrl_;
      valorIcmsBrl_ = other.valorIcmsBrl_;
      valorIcmsstBrl_ = other.valorIcmsstBrl_;
      valorIiBrl_ = other.valorIiBrl_;
      valorIpiBrl_ = other.valorIpiBrl_;
      valorPisBrl_ = other.valorPisBrl_;
      valorCofinsBrl_ = other.valorCofinsBrl_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NfItemMessage Clone() {
      return new NfItemMessage(this);
    }

    /// <summary>Field number for the "sku" field.</summary>
    public const int SkuFieldNumber = 1;
    private string sku_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sku {
      get { return sku_; }
      set {
        sku_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "descricao" field.</summary>
    public const int DescricaoFieldNumber = 2;
    private string descricao_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Descricao {
      get { return descricao_; }
      set {
        descricao_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "quantidade" field.</summary>
    public const int QuantidadeFieldNumber = 3;
    private int quantidade_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Quantidade {
      get { return quantidade_; }
      set {
        quantidade_ = value;
      }
    }

    /// <summary>Field number for the "valor_brl" field.</summary>
    public const int ValorBrlFieldNumber = 4;
    private int valorBrl_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ValorBrl {
      get { return valorBrl_; }
      set {
        valorBrl_ = value;
      }
    }

    /// <summary>Field number for the "valor_icms_brl" field.</summary>
    public const int ValorIcmsBrlFieldNumber = 5;
    private int valorIcmsBrl_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ValorIcmsBrl {
      get { return valorIcmsBrl_; }
      set {
        valorIcmsBrl_ = value;
      }
    }

    /// <summary>Field number for the "valor_icmsst_brl" field.</summary>
    public const int ValorIcmsstBrlFieldNumber = 6;
    private int valorIcmsstBrl_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ValorIcmsstBrl {
      get { return valorIcmsstBrl_; }
      set {
        valorIcmsstBrl_ = value;
      }
    }

    /// <summary>Field number for the "valor_ii_brl" field.</summary>
    public const int ValorIiBrlFieldNumber = 7;
    private int valorIiBrl_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ValorIiBrl {
      get { return valorIiBrl_; }
      set {
        valorIiBrl_ = value;
      }
    }

    /// <summary>Field number for the "valor_ipi_brl" field.</summary>
    public const int ValorIpiBrlFieldNumber = 8;
    private int valorIpiBrl_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ValorIpiBrl {
      get { return valorIpiBrl_; }
      set {
        valorIpiBrl_ = value;
      }
    }

    /// <summary>Field number for the "valor_pis_brl" field.</summary>
    public const int ValorPisBrlFieldNumber = 9;
    private int valorPisBrl_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ValorPisBrl {
      get { return valorPisBrl_; }
      set {
        valorPisBrl_ = value;
      }
    }

    /// <summary>Field number for the "valor_cofins_brl" field.</summary>
    public const int ValorCofinsBrlFieldNumber = 10;
    private int valorCofinsBrl_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ValorCofinsBrl {
      get { return valorCofinsBrl_; }
      set {
        valorCofinsBrl_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NfItemMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NfItemMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sku != other.Sku) return false;
      if (Descricao != other.Descricao) return false;
      if (Quantidade != other.Quantidade) return false;
      if (ValorBrl != other.ValorBrl) return false;
      if (ValorIcmsBrl != other.ValorIcmsBrl) return false;
      if (ValorIcmsstBrl != other.ValorIcmsstBrl) return false;
      if (ValorIiBrl != other.ValorIiBrl) return false;
      if (ValorIpiBrl != other.ValorIpiBrl) return false;
      if (ValorPisBrl != other.ValorPisBrl) return false;
      if (ValorCofinsBrl != other.ValorCofinsBrl) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Sku.Length != 0) hash ^= Sku.GetHashCode();
      if (Descricao.Length != 0) hash ^= Descricao.GetHashCode();
      if (Quantidade != 0) hash ^= Quantidade.GetHashCode();
      if (ValorBrl != 0) hash ^= ValorBrl.GetHashCode();
      if (ValorIcmsBrl != 0) hash ^= ValorIcmsBrl.GetHashCode();
      if (ValorIcmsstBrl != 0) hash ^= ValorIcmsstBrl.GetHashCode();
      if (ValorIiBrl != 0) hash ^= ValorIiBrl.GetHashCode();
      if (ValorIpiBrl != 0) hash ^= ValorIpiBrl.GetHashCode();
      if (ValorPisBrl != 0) hash ^= ValorPisBrl.GetHashCode();
      if (ValorCofinsBrl != 0) hash ^= ValorCofinsBrl.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Sku.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Sku);
      }
      if (Descricao.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Descricao);
      }
      if (Quantidade != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Quantidade);
      }
      if (ValorBrl != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ValorBrl);
      }
      if (ValorIcmsBrl != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ValorIcmsBrl);
      }
      if (ValorIcmsstBrl != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ValorIcmsstBrl);
      }
      if (ValorIiBrl != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ValorIiBrl);
      }
      if (ValorIpiBrl != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(ValorIpiBrl);
      }
      if (ValorPisBrl != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(ValorPisBrl);
      }
      if (ValorCofinsBrl != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(ValorCofinsBrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Sku.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Sku);
      }
      if (Descricao.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Descricao);
      }
      if (Quantidade != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Quantidade);
      }
      if (ValorBrl != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ValorBrl);
      }
      if (ValorIcmsBrl != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ValorIcmsBrl);
      }
      if (ValorIcmsstBrl != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ValorIcmsstBrl);
      }
      if (ValorIiBrl != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ValorIiBrl);
      }
      if (ValorIpiBrl != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(ValorIpiBrl);
      }
      if (ValorPisBrl != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(ValorPisBrl);
      }
      if (ValorCofinsBrl != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(ValorCofinsBrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Sku.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sku);
      }
      if (Descricao.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Descricao);
      }
      if (Quantidade != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quantidade);
      }
      if (ValorBrl != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ValorBrl);
      }
      if (ValorIcmsBrl != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ValorIcmsBrl);
      }
      if (ValorIcmsstBrl != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ValorIcmsstBrl);
      }
      if (ValorIiBrl != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ValorIiBrl);
      }
      if (ValorIpiBrl != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ValorIpiBrl);
      }
      if (ValorPisBrl != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ValorPisBrl);
      }
      if (ValorCofinsBrl != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ValorCofinsBrl);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NfItemMessage other) {
      if (other == null) {
        return;
      }
      if (other.Sku.Length != 0) {
        Sku = other.Sku;
      }
      if (other.Descricao.Length != 0) {
        Descricao = other.Descricao;
      }
      if (other.Quantidade != 0) {
        Quantidade = other.Quantidade;
      }
      if (other.ValorBrl != 0) {
        ValorBrl = other.ValorBrl;
      }
      if (other.ValorIcmsBrl != 0) {
        ValorIcmsBrl = other.ValorIcmsBrl;
      }
      if (other.ValorIcmsstBrl != 0) {
        ValorIcmsstBrl = other.ValorIcmsstBrl;
      }
      if (other.ValorIiBrl != 0) {
        ValorIiBrl = other.ValorIiBrl;
      }
      if (other.ValorIpiBrl != 0) {
        ValorIpiBrl = other.ValorIpiBrl;
      }
      if (other.ValorPisBrl != 0) {
        ValorPisBrl = other.ValorPisBrl;
      }
      if (other.ValorCofinsBrl != 0) {
        ValorCofinsBrl = other.ValorCofinsBrl;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Sku = input.ReadString();
            break;
          }
          case 18: {
            Descricao = input.ReadString();
            break;
          }
          case 24: {
            Quantidade = input.ReadInt32();
            break;
          }
          case 32: {
            ValorBrl = input.ReadInt32();
            break;
          }
          case 40: {
            ValorIcmsBrl = input.ReadInt32();
            break;
          }
          case 48: {
            ValorIcmsstBrl = input.ReadInt32();
            break;
          }
          case 56: {
            ValorIiBrl = input.ReadInt32();
            break;
          }
          case 64: {
            ValorIpiBrl = input.ReadInt32();
            break;
          }
          case 72: {
            ValorPisBrl = input.ReadInt32();
            break;
          }
          case 80: {
            ValorCofinsBrl = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Sku = input.ReadString();
            break;
          }
          case 18: {
            Descricao = input.ReadString();
            break;
          }
          case 24: {
            Quantidade = input.ReadInt32();
            break;
          }
          case 32: {
            ValorBrl = input.ReadInt32();
            break;
          }
          case 40: {
            ValorIcmsBrl = input.ReadInt32();
            break;
          }
          case 48: {
            ValorIcmsstBrl = input.ReadInt32();
            break;
          }
          case 56: {
            ValorIiBrl = input.ReadInt32();
            break;
          }
          case 64: {
            ValorIpiBrl = input.ReadInt32();
            break;
          }
          case 72: {
            ValorPisBrl = input.ReadInt32();
            break;
          }
          case 80: {
            ValorCofinsBrl = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NfMessage : pb::IMessage<NfMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NfMessage> _parser = new pb::MessageParser<NfMessage>(() => new NfMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NfMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Poc.EventDriven.Protos.NfIngress.V1.NfsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NfMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NfMessage(NfMessage other) : this() {
      chave_ = other.chave_;
      numero_ = other.numero_;
      serie_ = other.serie_;
      empresa_ = other.empresa_ != null ? other.empresa_.Clone() : null;
      exportador_ = other.exportador_ != null ? other.exportador_.Clone() : null;
      emissor_ = other.emissor_ != null ? other.emissor_.Clone() : null;
      emissao_ = other.emissao_ != null ? other.emissao_.Clone() : null;
      operacao_ = other.operacao_;
      items_ = other.items_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NfMessage Clone() {
      return new NfMessage(this);
    }

    /// <summary>Field number for the "chave" field.</summary>
    public const int ChaveFieldNumber = 1;
    private string chave_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Chave {
      get { return chave_; }
      set {
        chave_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "numero" field.</summary>
    public const int NumeroFieldNumber = 2;
    private int numero_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Numero {
      get { return numero_; }
      set {
        numero_ = value;
      }
    }

    /// <summary>Field number for the "serie" field.</summary>
    public const int SerieFieldNumber = 3;
    private int serie_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Serie {
      get { return serie_; }
      set {
        serie_ = value;
      }
    }

    /// <summary>Field number for the "empresa" field.</summary>
    public const int EmpresaFieldNumber = 4;
    private global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage empresa_;
    /// <summary>
    /// dimensões
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage Empresa {
      get { return empresa_; }
      set {
        empresa_ = value;
      }
    }

    /// <summary>Field number for the "exportador" field.</summary>
    public const int ExportadorFieldNumber = 5;
    private global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage exportador_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage Exportador {
      get { return exportador_; }
      set {
        exportador_ = value;
      }
    }

    /// <summary>Field number for the "emissor" field.</summary>
    public const int EmissorFieldNumber = 6;
    private global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage emissor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage Emissor {
      get { return emissor_; }
      set {
        emissor_ = value;
      }
    }

    /// <summary>Field number for the "emissao" field.</summary>
    public const int EmissaoFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp emissao_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Emissao {
      get { return emissao_; }
      set {
        emissao_ = value;
      }
    }

    /// <summary>Field number for the "operacao" field.</summary>
    public const int OperacaoFieldNumber = 8;
    private global::Poc.EventDriven.Protos.NfIngress.V1.NfTipoOperacao operacao_ = global::Poc.EventDriven.Protos.NfIngress.V1.NfTipoOperacao.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Poc.EventDriven.Protos.NfIngress.V1.NfTipoOperacao Operacao {
      get { return operacao_; }
      set {
        operacao_ = value;
      }
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Poc.EventDriven.Protos.NfIngress.V1.NfItemMessage> _repeated_items_codec
        = pb::FieldCodec.ForMessage(74, global::Poc.EventDriven.Protos.NfIngress.V1.NfItemMessage.Parser);
    private readonly pbc::RepeatedField<global::Poc.EventDriven.Protos.NfIngress.V1.NfItemMessage> items_ = new pbc::RepeatedField<global::Poc.EventDriven.Protos.NfIngress.V1.NfItemMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Poc.EventDriven.Protos.NfIngress.V1.NfItemMessage> Items {
      get { return items_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NfMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NfMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Chave != other.Chave) return false;
      if (Numero != other.Numero) return false;
      if (Serie != other.Serie) return false;
      if (!object.Equals(Empresa, other.Empresa)) return false;
      if (!object.Equals(Exportador, other.Exportador)) return false;
      if (!object.Equals(Emissor, other.Emissor)) return false;
      if (!object.Equals(Emissao, other.Emissao)) return false;
      if (Operacao != other.Operacao) return false;
      if(!items_.Equals(other.items_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Chave.Length != 0) hash ^= Chave.GetHashCode();
      if (Numero != 0) hash ^= Numero.GetHashCode();
      if (Serie != 0) hash ^= Serie.GetHashCode();
      if (empresa_ != null) hash ^= Empresa.GetHashCode();
      if (exportador_ != null) hash ^= Exportador.GetHashCode();
      if (emissor_ != null) hash ^= Emissor.GetHashCode();
      if (emissao_ != null) hash ^= Emissao.GetHashCode();
      if (Operacao != global::Poc.EventDriven.Protos.NfIngress.V1.NfTipoOperacao.Unspecified) hash ^= Operacao.GetHashCode();
      hash ^= items_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Chave.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Chave);
      }
      if (Numero != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Numero);
      }
      if (Serie != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Serie);
      }
      if (empresa_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Empresa);
      }
      if (exportador_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Exportador);
      }
      if (emissor_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Emissor);
      }
      if (emissao_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Emissao);
      }
      if (Operacao != global::Poc.EventDriven.Protos.NfIngress.V1.NfTipoOperacao.Unspecified) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Operacao);
      }
      items_.WriteTo(output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Chave.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Chave);
      }
      if (Numero != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Numero);
      }
      if (Serie != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Serie);
      }
      if (empresa_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Empresa);
      }
      if (exportador_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Exportador);
      }
      if (emissor_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Emissor);
      }
      if (emissao_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Emissao);
      }
      if (Operacao != global::Poc.EventDriven.Protos.NfIngress.V1.NfTipoOperacao.Unspecified) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Operacao);
      }
      items_.WriteTo(ref output, _repeated_items_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Chave.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Chave);
      }
      if (Numero != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Numero);
      }
      if (Serie != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Serie);
      }
      if (empresa_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Empresa);
      }
      if (exportador_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Exportador);
      }
      if (emissor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Emissor);
      }
      if (emissao_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Emissao);
      }
      if (Operacao != global::Poc.EventDriven.Protos.NfIngress.V1.NfTipoOperacao.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Operacao);
      }
      size += items_.CalculateSize(_repeated_items_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NfMessage other) {
      if (other == null) {
        return;
      }
      if (other.Chave.Length != 0) {
        Chave = other.Chave;
      }
      if (other.Numero != 0) {
        Numero = other.Numero;
      }
      if (other.Serie != 0) {
        Serie = other.Serie;
      }
      if (other.empresa_ != null) {
        if (empresa_ == null) {
          Empresa = new global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage();
        }
        Empresa.MergeFrom(other.Empresa);
      }
      if (other.exportador_ != null) {
        if (exportador_ == null) {
          Exportador = new global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage();
        }
        Exportador.MergeFrom(other.Exportador);
      }
      if (other.emissor_ != null) {
        if (emissor_ == null) {
          Emissor = new global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage();
        }
        Emissor.MergeFrom(other.Emissor);
      }
      if (other.emissao_ != null) {
        if (emissao_ == null) {
          Emissao = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Emissao.MergeFrom(other.Emissao);
      }
      if (other.Operacao != global::Poc.EventDriven.Protos.NfIngress.V1.NfTipoOperacao.Unspecified) {
        Operacao = other.Operacao;
      }
      items_.Add(other.items_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Chave = input.ReadString();
            break;
          }
          case 16: {
            Numero = input.ReadInt32();
            break;
          }
          case 24: {
            Serie = input.ReadInt32();
            break;
          }
          case 34: {
            if (empresa_ == null) {
              Empresa = new global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage();
            }
            input.ReadMessage(Empresa);
            break;
          }
          case 42: {
            if (exportador_ == null) {
              Exportador = new global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage();
            }
            input.ReadMessage(Exportador);
            break;
          }
          case 50: {
            if (emissor_ == null) {
              Emissor = new global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage();
            }
            input.ReadMessage(Emissor);
            break;
          }
          case 58: {
            if (emissao_ == null) {
              Emissao = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Emissao);
            break;
          }
          case 64: {
            Operacao = (global::Poc.EventDriven.Protos.NfIngress.V1.NfTipoOperacao) input.ReadEnum();
            break;
          }
          case 74: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Chave = input.ReadString();
            break;
          }
          case 16: {
            Numero = input.ReadInt32();
            break;
          }
          case 24: {
            Serie = input.ReadInt32();
            break;
          }
          case 34: {
            if (empresa_ == null) {
              Empresa = new global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage();
            }
            input.ReadMessage(Empresa);
            break;
          }
          case 42: {
            if (exportador_ == null) {
              Exportador = new global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage();
            }
            input.ReadMessage(Exportador);
            break;
          }
          case 50: {
            if (emissor_ == null) {
              Emissor = new global::Poc.EventDriven.Protos.NfIngress.V1.NfEmpresaMessage();
            }
            input.ReadMessage(Emissor);
            break;
          }
          case 58: {
            if (emissao_ == null) {
              Emissao = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Emissao);
            break;
          }
          case 64: {
            Operacao = (global::Poc.EventDriven.Protos.NfIngress.V1.NfTipoOperacao) input.ReadEnum();
            break;
          }
          case 74: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
