apiVersion: apps/v1
kind: Deployment
metadata:
  name: regime-api-dep
  namespace: poc-event-driven-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regime-api-app
  template:
    metadata:
      labels:
        app: regime-api-app
    spec:
      containers:
      - name: regime-api-dep
        image: maxandriani/poc.eventdriven.app.regimeapi:1.0.0
        envFrom:
          - configMapRef:
              name: regime-api-config
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: regime-api-port
