apiVersion: v1
kind: Service
metadata:
  name: regime-api-svc
  namespace: poc-event-driven-ns
spec:
  type: LoadBalancer
  selector:
    app: regime-api-app
  ports:
  - port: 5001
    targetPort: regime-api-port
